# Welcome to Ambisnail - A Simple website

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Connor Wang # Title of your Website. Eg: Connor's Website
email: connor.wang@ualberta.ca # Your email
contact-email: connor.wang@ualberta.ca # Email for contact page. Can be your email.
author: Connor Yimin Wang
description: > # this means to ignore newlines until "baseurl:"
  Ambisnail is a small website. Suitable for personal Websites & Blogs.
url: "https://ambisnail.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

includes_dir: .

# Sharing settings
shareimg: assets/images/homepage.jpg # default sharing img
bigimg: images/patterns/triangular.png # default big img (header image(s))
fb_app_id: 12345 # Facebook app id

timezone: "MST"
permalink: posts/:title.html

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
